# Site settings
title: KWSP (EPF) Contribution Calculator
description: Calculate your Employees Provident Fund (EPF) contributions based on your monthly salary in Malaysia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Minima theme settings
minima:
  # social_links:
  #   - { platform: github,  user_url: "https://github.com/yourusername" }

# Enable post excerpts
show_excerpts: false

# Permalink style
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
